language: php
php:
  - '7.4'

addons:
  apt:
    packages:
      - graphviz

before_script: 
  - pear channel-discover pear.phpdoc.org
  - pear install phpdoc/phpDocumentor

script: phpdoc -d ./src -t ./docs

deploy:
- provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: "./docs/"
  skip-cleanup: true
  on:
    branch: master